DROP VIEW IF EXISTS Profile;


DROP TABLE if EXISTS Messages;
DROP TABLE if EXISTS TGroupMembers;
DROP TABLE if EXISTS TGroups;
DROP TABLE if EXISTS Orders;
DROP TABLE if EXISTS UAuthentication;
DROP TABLE if EXISTS Users;
DROP TABLE if EXISTS Payment;
DROP TABLE if EXISTS Product;
DROP TABLE if EXISTS Supplier;
DROP TABLE if EXISTS Insurance;
DROP TABLE if EXISTS Alarm;


-- PROCEDURES
DROP PROCEDURE if EXISTS CheckPasswordValidity;
DROP PROCEDURE if EXISTS CreateChat;

